import type { Beispiel } from "./typen";

/**
 * Beispiele für den Einstieg. Neue Beispiele einfach unten anhängen –
 * das Validierungsskript prüft Pflichtfelder und Tags beim Build.
 */
export const beispiele: Beispiel[] = [
  {
    id: "website",
    titel: "Deine persönliche Website",
    kurz: "Eine einseitige Website über dich oder dein Angebot – ohne vorher programmieren zu lernen.",
    warumNuetzlich: "Du siehst sofort ein Ergebnis im Browser und lernst dabei den ganzen Ablauf kennen.",
    schwierigkeit: "leicht",
    dauerMin: 30,
    tags: ["bauen", "lernen", "selbststaendig", "kreativ", "marketing", "studium", "sonstiges"],
    brauchtGithub: false,
    brauchtMcp: false,
    ersterPrompt:
      "Ich möchte eine einfache persönliche Website als eine einzige HTML-Datei. Sie soll meinen Namen, drei Sätze über mich und einen Kontakt-Knopf zeigen. Stell mir zuerst bis zu 5 Fragen zu Farben und Inhalt, mache dann einen Plan und ändere noch nichts, bevor ich zustimme.",
    fertigWenn: "Du öffnest die Datei per Doppelklick im Browser und siehst deine Seite mit deinem Namen.",
    sensibel: false,
    dummyDatenHinweis: "",
    icon: "globe",
  },
  {
    id: "downloads-aufraeumen",
    titel: "Downloads-Ordner aufräumen",
    kurz: "Claude sortiert einen unordentlichen Ordner nach Dateityp in Unterordner.",
    warumNuetzlich: "Schnell erledigt und du siehst direkt, wie Claude mit Dateien umgeht.",
    schwierigkeit: "leicht",
    dauerMin: 10,
    tags: ["ordnen", "buero", "lernen", "sonstiges", "studium"],
    brauchtGithub: false,
    brauchtMcp: false,
    ersterPrompt:
      "In diesem Ordner liegen viele gemischte Dateien. Zeig mir zuerst eine Liste, wie du sie in Unterordner wie „Bilder“, „PDFs“ und „Tabellen“ sortieren würdest. Verschiebe noch nichts und lösche niemals etwas, bevor ich zustimme.",
    fertigWenn: "Alle Dateien liegen in passenden Unterordnern und keine Datei fehlt.",
    sensibel: false,
    dummyDatenHinweis: "",
    icon: "folder",
  },
  {
    id: "tabelle-bereinigen",
    titel: "Chaotische Tabelle bereinigen",
    kurz: "Einheitliche Datumsformate, keine doppelten Leerzeichen, saubere Spalten.",
    warumNuetzlich: "Spart stundenlanges Nacharbeiten per Hand – und das Original bleibt erhalten.",
    schwierigkeit: "leicht",
    dauerMin: 10,
    tags: ["ordnen", "buero", "marketing", "gesundheit", "sonstiges"],
    brauchtGithub: false,
    brauchtMcp: false,
    ersterPrompt:
      "Im Ordner liegt eine Tabelle als CSV-Datei. Bitte vereinheitliche alle Datumsangaben auf TT.MM.JJJJ und entferne überflüssige Leerzeichen. Speichere das Ergebnis als neue Datei und lass das Original unverändert. Zeig mir zuerst an drei Zeilen, was du ändern würdest.",
    fertigWenn: "Eine neue Datei existiert, alle Daten haben dasselbe Format und das Original ist unverändert.",
    sensibel: false,
    dummyDatenHinweis: "",
    icon: "table",
  },
  {
    id: "zitat-generator",
    titel: "Zitat-Generator aus deiner Sammlung",
    kurz: "Eine kleine Webseite zeigt per Knopfdruck ein zufälliges Zitat aus deiner Liste.",
    warumNuetzlich: "Ein schnelles, schönes Erfolgserlebnis mit deinen eigenen Inhalten.",
    schwierigkeit: "leicht",
    dauerMin: 15,
    tags: ["bauen", "lernen", "kreativ", "studium", "sonstiges"],
    brauchtGithub: false,
    brauchtMcp: false,
    ersterPrompt:
      "Ich habe eine Textdatei mit Zitaten, eins pro Zeile. Baue mir eine einzelne HTML-Seite, die per Knopfdruck ein zufälliges Zitat groß und schön anzeigt. Stell mir zuerst bis zu 3 Fragen zum Aussehen, dann mache einen Plan.",
    fertigWenn: "Du klickst den Knopf im Browser und bekommst jedes Mal ein anderes Zitat aus deiner Liste.",
    sensibel: false,
    dummyDatenHinweis: "",
    icon: "quote",
  },
  {
    id: "foto-organizer",
    titel: "Fotos und Dateien umbenennen",
    kurz: "Einheitliche Dateinamen mit Datum, sortiert nach Jahr und Monat.",
    warumNuetzlich: "Du findest Fotos und Scans später in Sekunden statt Minuten.",
    schwierigkeit: "mittel",
    dauerMin: 30,
    tags: ["ordnen", "kreativ", "buero", "sonstiges"],
    brauchtGithub: false,
    brauchtMcp: false,
    ersterPrompt:
      "In diesem Ordner liegen Fotos mit Namen wie IMG_1234.jpg. Ich möchte sie in „JJJJ-MM-TT_Beschreibung.jpg“ umbenennen und nach Jahr/Monat sortieren. Arbeite zuerst an einer Kopie von 5 Fotos, zeig mir das Ergebnis und warte auf mein OK, bevor du alle umbenennst.",
    fertigWenn: "Die Testkopie ist korrekt umbenannt und du hast das Vorgehen für alle Dateien freigegeben.",
    sensibel: false,
    dummyDatenHinweis: "",
    icon: "image",
  },
  {
    id: "notizen-bericht",
    titel: "Notizen werden zum Kurzbericht",
    kurz: "Aus einem Ordner voller Notizen entsteht eine Zusammenfassung mit Dateinamen als Beleg.",
    warumNuetzlich: "Du siehst bei jeder Aussage, aus welcher Notiz sie stammt – nichts ist erfunden.",
    schwierigkeit: "leicht",
    dauerMin: 15,
    tags: ["schreiben", "buero", "studium", "gesundheit", "marketing"],
    brauchtGithub: false,
    brauchtMcp: false,
    ersterPrompt:
      "Lies alle Notizen in diesem Ordner und schreibe einen Kurzbericht mit höchstens einer Seite. Nenne hinter jeder Aussage in Klammern den Dateinamen, aus dem sie stammt. Erfinde nichts, was nicht in den Notizen steht.",
    fertigWenn: "Der Bericht ist höchstens eine Seite lang und jede Aussage hat einen Dateinamen als Beleg.",
    sensibel: true,
    dummyDatenHinweis:
      "Enthalten deine Notizen Namen von Kunden oder Patienten, übe zuerst mit erfundenen Notizen. Claude kann dir welche erstellen.",
    icon: "notebook",
  },
  {
    id: "recherche-zusammenfassung",
    titel: "Recherche-Ordner zusammenfassen",
    kurz: "PDFs und Texte werden zu einer Übersicht mit Quellenangaben.",
    warumNuetzlich: "Ideal für Hausarbeiten, Marktrecherchen und Entscheidungsvorlagen.",
    schwierigkeit: "mittel",
    dauerMin: 45,
    tags: ["schreiben", "studium", "marketing", "selbststaendig", "lernen"],
    brauchtGithub: false,
    brauchtMcp: false,
    ersterPrompt:
      "In diesem Ordner liegen Texte und PDFs zu einem Thema. Erstelle eine Zusammenfassung mit den 5 wichtigsten Erkenntnissen. Gib zu jeder Erkenntnis die Quelle (Dateiname und Seite) an. Markiere klar, wenn sich Quellen widersprechen.",
    fertigWenn: "Du hast 5 Erkenntnisse mit Quellen und kannst jede davon in der Originaldatei wiederfinden.",
    sensibel: false,
    dummyDatenHinweis: "",
    icon: "search",
  },
  {
    id: "wochenbericht",
    titel: "Wochenbericht oder Newsletter-Entwurf",
    kurz: "Aus vorhandenen Zahlen und Stichpunkten entsteht jede Woche ein fertiger Entwurf.",
    warumNuetzlich: "Wiederkehrende Schreibarbeit wird zur Routine von fünf Minuten.",
    schwierigkeit: "mittel",
    dauerMin: 30,
    tags: ["schreiben", "buero", "marketing", "selbststaendig"],
    brauchtGithub: false,
    brauchtMcp: false,
    ersterPrompt:
      "Im Ordner liegen meine Stichpunkte und eine Tabelle mit Zahlen dieser Woche. Schreibe daraus einen freundlichen Wochenbericht mit höchstens 200 Wörtern. Stell mir zuerst Fragen zu Ton und Zielgruppe. Erfinde keine Zahlen.",
    fertigWenn: "Der Entwurf hat höchstens 200 Wörter und alle Zahlen stimmen mit der Tabelle überein.",
    sensibel: false,
    dummyDatenHinweis: "",
    icon: "mail",
  },
  {
    id: "ausgaben-tracker",
    titel: "Ausgaben-Tracker aus dem Kontoauszug",
    kurz: "Ein Kontoauszug als CSV wird automatisch in Kategorien wie Miete, Essen und Freizeit sortiert.",
    warumNuetzlich: "Du siehst auf einen Blick, wohin dein Geld geht.",
    schwierigkeit: "mittel",
    dauerMin: 45,
    tags: ["ordnen", "selbststaendig", "buero", "bauen", "sonstiges"],
    brauchtGithub: false,
    brauchtMcp: false,
    ersterPrompt:
      "Im Ordner liegt ein Kontoauszug als CSV. Ordne jede Buchung einer Kategorie zu (Miete, Lebensmittel, Freizeit, Sonstiges) und erstelle eine Übersicht mit der Summe pro Kategorie. Zeig mir zuerst deine Regeln für die Zuordnung, bevor du rechnest.",
    fertigWenn: "Jede Buchung hat eine Kategorie und die Summe aller Kategorien entspricht der Gesamtsumme.",
    sensibel: true,
    dummyDatenHinweis:
      "Kontoauszüge sind Finanzdaten. Übe zuerst mit einem erfundenen Auszug – bitte Claude, dir einen mit 20 Beispielbuchungen zu erstellen.",
    icon: "wallet",
  },
  {
    id: "csv-dashboard",
    titel: "Kleines Dashboard aus einer CSV",
    kurz: "Aus einer Tabelle wird eine Webseite mit Diagrammen und Kennzahlen.",
    warumNuetzlich: "Zahlen werden verständlich – ideal für Besprechungen und eigene Auswertungen.",
    schwierigkeit: "mittel",
    dauerMin: 60,
    tags: ["bauen", "marketing", "buero", "it", "selbststaendig"],
    brauchtGithub: false,
    brauchtMcp: false,
    ersterPrompt:
      "Im Ordner liegt eine CSV-Datei mit Verkaufszahlen. Baue eine einzelne HTML-Seite, die drei Kennzahlen und ein Balkendiagramm zeigt. Prüfe am Ende selbst, ob die Summen mit der CSV übereinstimmen, und zeig mir das Ergebnis der Prüfung.",
    fertigWenn: "Die Seite öffnet sich im Browser und die Kennzahlen stimmen mit der CSV überein.",
    sensibel: false,
    dummyDatenHinweis: "",
    icon: "chart",
  },
  {
    id: "browser-spiel",
    titel: "Kleines Browser-Spiel",
    kurz: "Ein Retro-Shooter oder Memory-Spiel, das direkt im Browser läuft.",
    warumNuetzlich: "Macht Spaß und zeigt, wie Claude in kleinen Runden baut, testet und verbessert.",
    schwierigkeit: "mittel",
    dauerMin: 60,
    tags: ["bauen", "lernen", "kreativ", "studium"],
    brauchtGithub: false,
    brauchtMcp: false,
    ersterPrompt:
      "Baue ein kleines Retro-Weltraumspiel als einzelne HTML-Datei: Ein Raumschiff unten bewegt sich mit den Pfeiltasten und schießt mit der Leertaste auf fallende Steine. Mache zuerst einen Plan in kleinen Schritten und baue dann Schritt für Schritt.",
    fertigWenn: "Du kannst das Spiel im Browser starten, dich bewegen, schießen und Punkte sammeln.",
    sensibel: false,
    dummyDatenHinweis: "",
    icon: "gamepad",
  },
  {
    id: "readme-generieren",
    titel: "README für ein bestehendes Projekt",
    kurz: "Claude liest ein Code-Projekt und schreibt eine verständliche Anleitung dazu.",
    warumNuetzlich: "Der schnellste Weg, ein fremdes Projekt zu verstehen – und es anderen zu erklären.",
    schwierigkeit: "leicht",
    dauerMin: 10,
    tags: ["programmieren", "it", "schreiben"],
    brauchtGithub: false,
    brauchtMcp: false,
    ersterPrompt:
      "Lies dieses Projekt und schreibe eine README.md mit: Was macht das Projekt, wie installiere ich es, wie starte ich es, wie führe ich die Tests aus. Prüfe jeden Befehl, den du nennst, indem du ihn ausführst oder in den Dateien nachsiehst.",
    fertigWenn: "Die README existiert und jeder genannte Befehl funktioniert, wenn du ihn ausprobierst.",
    sensibel: false,
    dummyDatenHinweis: "",
    icon: "book",
  },
  {
    id: "tests-schreiben",
    titel: "Tests schreiben und ausführen",
    kurz: "Claude schreibt Tests für ungetesteten Code, führt sie aus und behebt Fehler.",
    warumNuetzlich: "Tests geben Claude eine Möglichkeit, die eigene Arbeit zu prüfen – das verbessert alles Weitere.",
    schwierigkeit: "fortgeschritten",
    dauerMin: 60,
    tags: ["programmieren", "it"],
    brauchtGithub: false,
    brauchtMcp: false,
    ersterPrompt:
      "Finde eine wichtige Funktion ohne Tests. Schlage zuerst 5 Testfälle inklusive Randfällen vor. Nach meiner Zustimmung schreibst du die Tests, führst sie aus und zeigst mir die Ausgabe.",
    fertigWenn: "Die neuen Tests laufen durch und du hast die Ausgabe des Testlaufs gesehen.",
    sensibel: false,
    dummyDatenHinweis: "",
    icon: "flask",
  },
  {
    id: "code-review",
    titel: "Code-Review deiner Änderungen",
    kurz: "Claude prüft deine letzten Änderungen auf Fehler, Sicherheitslücken und Unklarheiten.",
    warumNuetzlich: "Eine zweite Meinung in Sekunden, bevor du etwas veröffentlichst.",
    schwierigkeit: "fortgeschritten",
    dauerMin: 30,
    tags: ["programmieren", "it"],
    brauchtGithub: true,
    brauchtMcp: false,
    ersterPrompt:
      "Prüfe meine Änderungen seit dem letzten Commit. Liste nur echte Probleme auf: Fehler, Sicherheitsrisiken, fehlende Randfälle. Nenne zu jedem Problem die Datei und Zeile. Ändere noch nichts.",
    fertigWenn: "Du hast eine Liste mit Datei und Zeile zu jedem Fund und entschieden, was du beheben willst.",
    sensibel: false,
    dummyDatenHinweis: "",
    icon: "check-circle",
  },
  {
    id: "angebot-rechnung",
    titel: "Angebots- und Rechnungsvorlage als Tool",
    kurz: "Ein kleines Formular erzeugt aus wenigen Angaben ein sauberes Angebot zum Drucken.",
    warumNuetzlich: "Einheitliche, professionelle Dokumente – ohne jedes Mal Word-Vorlagen zu kopieren.",
    schwierigkeit: "mittel",
    dauerMin: 60,
    tags: ["bauen", "selbststaendig", "buero"],
    brauchtGithub: false,
    brauchtMcp: false,
    ersterPrompt:
      "Baue mir eine einzelne HTML-Seite mit einem Formular für Kunde, Leistungen, Menge und Preis. Daraus soll ein druckfertiges Angebot mit Summe und Mehrwertsteuer entstehen. Nutze nur erfundene Beispieldaten. Stell mir zuerst bis zu 5 Fragen.",
    fertigWenn: "Du füllst das Formular aus, die Summe stimmt und die Druckansicht passt auf eine Seite.",
    sensibel: true,
    dummyDatenHinweis:
      "Nutze erfundene Kunden und Beträge, bis das Tool fertig ist. Echte Kundendaten gehören nicht in den Chat.",
    icon: "receipt",
  },
  {
    id: "belege-sortieren",
    titel: "Belege und Rechnungen sortieren",
    kurz: "PDF-Belege werden nach Monat und Art sortiert und in einer Liste erfasst.",
    warumNuetzlich: "Die Steuererklärung oder Buchhaltung wird deutlich entspannter.",
    schwierigkeit: "mittel",
    dauerMin: 45,
    tags: ["ordnen", "buero", "selbststaendig"],
    brauchtGithub: false,
    brauchtMcp: false,
    ersterPrompt:
      "In diesem Ordner liegen erfundene Beispiel-Belege als PDF. Sortiere sie in Unterordner nach Monat und erstelle eine Tabelle mit Datum, Absender und Betrag. Zeig mir zuerst deinen Plan und lösche niemals etwas.",
    fertigWenn: "Jeder Beleg liegt im richtigen Monatsordner und steht mit Betrag in der Tabelle.",
    sensibel: true,
    dummyDatenHinweis:
      "Nur mit Dummy-Daten üben! Bitte Claude, dir zuerst 10 erfundene Belege zu erstellen. Echte Belege erst, wenn du den Ablauf verstehst und es erlaubt ist.",
    icon: "file-stack",
  },
];

export function findeBeispiel(id: string): Beispiel | undefined {
  return beispiele.find((b) => b.id === id);
}
