import type { Frage } from "./typen";

export const bloecke = {
  1: "Wer bist du?",
  2: "Was willst du erreichen?",
  3: "Deine Ausstattung",
  4: "Wie lernst du am liebsten?",
} as const;

export const fragen: Frage[] = [
  // ---------- Block 1 ----------
  {
    id: "name",
    block: 1,
    frage: "Wie sollen wir dich nennen?",
    warum: "Damit dein Plan dich direkt anspricht. Der Name bleibt nur in deinem Browser.",
    typ: "text",
    pflicht: false,
    platzhalter: ["Alex", "Sam", "Mika"],
    standard: "",
  },
  {
    id: "bereich",
    block: 1,
    frage: "In welchem Bereich arbeitest du?",
    warum: "So wählen wir Beispiele aus, die zu deinem Alltag passen.",
    typ: "einzel",
    pflicht: false,
    standard: "sonstiges",
    optionen: [
      { wert: "buero", label: "Büro & Verwaltung", icon: "briefcase" },
      { wert: "it", label: "IT & Technik", icon: "cpu" },
      { wert: "marketing", label: "Marketing & Vertrieb", icon: "megaphone" },
      { wert: "selbststaendig", label: "Selbstständig / Gründung", icon: "rocket" },
      { wert: "studium", label: "Studium & Schule", icon: "graduation" },
      { wert: "kreativ", label: "Kreativ & Medien", icon: "palette" },
      { wert: "gesundheit", label: "Gesundheit & Pflege", icon: "heart" },
      { wert: "sonstiges", label: "Sonstiges", icon: "sparkles" },
    ],
  },
  {
    id: "code",
    block: 1,
    frage: "Wie viel Programmiererfahrung hast du?",
    warum: "Davon hängt ab, wie viele Fachbegriffe wir erklären und welche Verbindungen sinnvoll sind.",
    typ: "einzel",
    pflicht: true,
    optionen: [
      { wert: "keine", label: "Keine", hinweis: "Ich habe noch nie programmiert.", icon: "seedling" },
      { wert: "etwas", label: "Etwas", hinweis: "Mal ein Skript oder etwas HTML.", icon: "sprout" },
      { wert: "gut", label: "Gut", hinweis: "Ich programmiere regelmäßig.", icon: "tree" },
    ],
  },
  {
    id: "ki",
    block: 1,
    frage: "Wie viel KI nutzt du schon?",
    warum: "So wissen wir, wo deine Anleitung anfangen soll.",
    typ: "einzel",
    pflicht: false,
    standard: "chat",
    optionen: [
      { wert: "chat", label: "Nur Chat-Assistenten", hinweis: "Zum Beispiel ChatGPT oder Claude im Browser.", icon: "message" },
      { wert: "claude", label: "Claude regelmäßig", icon: "sparkles" },
      { wert: "claudecode", label: "Claude Code schon probiert", icon: "terminal" },
    ],
  },
  {
    id: "terminal",
    block: 1,
    frage: "Wie geht es dir mit dem Terminal?",
    erklaerung:
      "Das [[terminal|Terminal]] ist ein Fenster, in das du Befehle als Text tippst statt zu klicken.",
    warum: "Davon hängt ab, ob wir dir die Desktop-App oder das Terminal empfehlen.",
    typ: "einzel",
    pflicht: true,
    optionen: [
      { wert: "nie", label: "Noch nie benutzt", icon: "eye-off" },
      { wert: "schonmal", label: "Schon mal", hinweis: "Ein paar Befehle abgetippt.", icon: "terminal" },
      { wert: "sicher", label: "Sicher", hinweis: "Ich bewege mich dort gern.", icon: "zap" },
    ],
  },

  // ---------- Block 2 ----------
  {
    id: "ziel",
    block: 2,
    frage: "Was willst du hauptsächlich tun?",
    warum: "Deine Ziele bestimmen Beispiele und Verbindungen. Wähl höchstens zwei.",
    typ: "mehrfach",
    pflicht: true,
    maxAuswahl: 2,
    optionen: [
      { wert: "bauen", label: "Etwas bauen", hinweis: "Website, App, kleines Tool", icon: "hammer" },
      { wert: "buero", label: "Zeit bei Büroaufgaben sparen", icon: "clock" },
      { wert: "ordnen", label: "Dateien & Daten ordnen", icon: "folder" },
      { wert: "schreiben", label: "Recherchieren & schreiben", icon: "pen" },
      { wert: "programmieren", label: "Schneller programmieren", icon: "code" },
      { wert: "lernen", label: "Erst mal lernen & ausprobieren", icon: "graduation" },
      { wert: "unklar", label: "Weiß ich noch nicht", icon: "compass", exklusiv: true },
    ],
  },
  {
    id: "idee",
    block: 2,
    frage: "Deine Idee in einem Satz?",
    warum: "Daraus bauen wir deinen ersten Prompt, den du nur noch kopieren musst.",
    typ: "text",
    pflicht: false,
    standard: "",
    platzhalter: [
      "eine Website für meinen Yoga-Kurs",
      "meine Rechnungen nach Monat sortieren",
      "aus meinen Notizen einen Wochenbericht machen",
    ],
  },
  {
    id: "haeufigkeit",
    block: 2,
    frage: "Einmalig oder immer wieder?",
    warum: "Für wiederkehrende Aufgaben zeigen wir dir, wie du Anleitungen speicherst und Aufgaben planst.",
    typ: "einzel",
    pflicht: false,
    standard: "einmalig",
    optionen: [
      { wert: "einmalig", label: "Einmalig", icon: "target" },
      { wert: "wiederkehrend", label: "Immer wieder", icon: "repeat" },
      { wert: "beides", label: "Beides", icon: "layers" },
    ],
  },

  // ---------- Block 3 ----------
  {
    id: "os",
    block: 3,
    frage: "Welches Gerät nutzt du?",
    warum: "Befehle und Installation unterscheiden sich je nach System.",
    typ: "einzel",
    pflicht: true,
    optionen: [
      { wert: "windows", label: "Windows", icon: "monitor" },
      { wert: "mac", label: "Mac", icon: "laptop" },
      { wert: "linux", label: "Linux", icon: "server" },
      { wert: "mobil", label: "Nur Handy / Tablet", icon: "smartphone" },
    ],
  },
  {
    id: "abo",
    block: 3,
    frage: "Welchen Claude-Zugang hast du?",
    warum: "Die meisten Zugänge zu Claude Code brauchen ein Abo oder ein Console-Konto. Das klären wir ganz am Anfang.",
    typ: "einzel",
    pflicht: true,
    optionen: [
      { wert: "keins", label: "Noch keinen", icon: "circle" },
      { wert: "gratis", label: "Gratis-Konto", icon: "gift" },
      { wert: "pro", label: "Pro", icon: "star" },
      { wert: "max", label: "Max", icon: "stars" },
      { wert: "team", label: "Team / Enterprise", icon: "users" },
      { wert: "api", label: "API- / Console-Konto", icon: "key" },
      { wert: "unbekannt", label: "Weiß ich nicht", icon: "help" },
    ],
  },
  {
    id: "github",
    block: 3,
    frage: "Hast du ein GitHub-Konto?",
    erklaerung:
      "GitHub ist ein Online-Dienst, der deine Projekte als [[repository|Repository]] sicher aufbewahrt – mit allen Versionen.",
    warum: "Mit GitHub hast du eine Sicherungskopie und kannst Claude Code auch im Web nutzen.",
    typ: "einzel",
    pflicht: true,
    optionen: [
      { wert: "nein", label: "Nein", icon: "x" },
      { wert: "ja", label: "Ja", icon: "check" },
      { wert: "unbekannt", label: "Was ist das?", hinweis: "Kein Problem, wir erklären es dir im Plan.", icon: "help" },
    ],
  },
  {
    id: "rechner",
    block: 3,
    frage: "Auf welchem Rechner arbeitest du?",
    warum: "Auf Firmenrechnern darf man oft nicht alles installieren. Dann sagen wir dir, was du vorher klären solltest.",
    typ: "einzel",
    pflicht: false,
    standard: "privat",
    optionen: [
      { wert: "privat", label: "Privat", icon: "home" },
      { wert: "firma", label: "Firmenrechner mit Einschränkungen", icon: "building" },
      { wert: "beides", label: "Beides", icon: "layers" },
    ],
  },
  {
    id: "tools",
    block: 3,
    frage: "Welche Programme nutzt du im Alltag?",
    warum: "Passende Verbindungen ([[mcp|MCP]]) holen Daten aus diesen Programmen direkt zu Claude.",
    typ: "mehrfach",
    pflicht: false,
    standard: ["keine"],
    optionen: [
      { wert: "google", label: "Google Drive / Docs", icon: "file" },
      { wert: "notion", label: "Notion", icon: "notebook" },
      { wert: "slack", label: "Slack", icon: "message" },
      { wert: "kalendermail", label: "Kalender & Mail", icon: "calendar" },
      { wert: "jiralinear", label: "Jira / Linear", icon: "kanban" },
      { wert: "datenbank", label: "Datenbank", icon: "database" },
      { wert: "keine", label: "Keine davon", icon: "circle", exklusiv: true },
    ],
  },
  {
    id: "sensibel",
    block: 3,
    frage: "Arbeitest du mit sensiblen Daten?",
    erklaerung: "Zum Beispiel Kunden-, Patienten-, Firmen- oder Finanzdaten.",
    warum: "Dann empfehlen wir einen vorsichtigeren Modus und das Üben mit erfundenen Daten.",
    typ: "einzel",
    pflicht: true,
    optionen: [
      { wert: "nein", label: "Nein", icon: "check" },
      { wert: "manchmal", label: "Manchmal", icon: "alert" },
      { wert: "ja", label: "Ja", icon: "shield" },
    ],
  },

  // ---------- Block 4 ----------
  {
    id: "zeit",
    block: 4,
    frage: "Wie viel Zeit hast du pro Sitzung?",
    warum: "Wir schlagen dir Beispiele vor, die in deine Zeit passen.",
    typ: "einzel",
    pflicht: false,
    standard: "1h",
    optionen: [
      { wert: "10min", label: "10 Minuten", icon: "timer" },
      { wert: "1h", label: "1 Stunde", icon: "clock" },
      { wert: "abend", label: "Ein Abend", icon: "moon" },
      { wert: "wochenende", label: "Wochenende", icon: "sun" },
    ],
  },
  {
    id: "lernstil",
    block: 4,
    frage: "Wie lernst du am liebsten?",
    warum: "Danach richten wir den Aufbau deiner Schritt-für-Schritt-Anleitung aus.",
    typ: "einzel",
    pflicht: false,
    standard: "klein",
    optionen: [
      { wert: "klein", label: "Ganz kleine Schritte", icon: "footprints" },
      { wert: "ueberblick", label: "Überblick, dann selbst probieren", icon: "map" },
      { wert: "beispiel", label: "Erst ein Beispiel sehen", icon: "eye" },
    ],
  },
  {
    id: "kontrolle",
    block: 4,
    frage: "Wie viel Kontrolle willst du behalten?",
    erklaerung:
      "Der [[berechtigungsmodus|Berechtigungsmodus]] legt fest, was Claude ohne Nachfrage tun darf.",
    warum: "Daraus leiten wir deinen empfohlenen Berechtigungsmodus ab – mit Erklärung.",
    typ: "einzel",
    pflicht: false,
    standard: "jeder",
    optionen: [
      { wert: "jeder", label: "Jeden Schritt bestätigen", icon: "hand" },
      { wert: "ausgewogen", label: "Ausgewogen", icon: "scale" },
      { wert: "selbst", label: "Möglichst selbstständig", icon: "zap" },
    ],
  },
  {
    id: "kosten",
    block: 4,
    frage: "Wie wichtig ist dir Kostenkontrolle?",
    warum: "Dann bekommst du Spar-Tipps und siehst, wie du deinen Verbrauch im Blick behältst.",
    typ: "einzel",
    pflicht: false,
    standard: "etwas",
    optionen: [
      { wert: "sehr", label: "Sehr wichtig", icon: "piggy" },
      { wert: "etwas", label: "Etwas", icon: "coins" },
      { wert: "egal", label: "Egal", icon: "smile" },
    ],
  },
];

export function findeFrage(id: string): Frage | undefined {
  return fragen.find((f) => f.id === id);
}
