import type { Mcp } from "./typen";
import { DOKU } from "./fakten";

/** Sichtbar in jedem MCP-Eintrag. */
export const TOKEN_REGEL =
  "Zugangsdaten und Tokens gehören niemals in den Chat oder in Dateien im Projekt.";

export const WENIGER_IST_MEHR =
  "Wenige, dafür passende Verbindungen: Jede Verbindung belegt etwas [[kontext|Kontext]]. Schalte ungenutzte mit `/mcp` ab.";

const CONNECTORS = "https://claude.com/docs/connectors";

export const mcps: Mcp[] = [
  {
    id: "github",
    name: "GitHub",
    wozu: "Claude liest und bearbeitet Code, Issues und Pull Requests auf GitHub.",
    fuerWen: "Alle, die ihre Projekte auf GitHub ablegen und dort zusammenarbeiten.",
    voraussetzung: "Ein GitHub-Konto.",
    risiko: "Claude kann in deinem Namen auf GitHub schreiben. Gib nur die Rechte frei, die du wirklich brauchst.",
    wannNicht:
      "Oft unnötig: Claude Code bedient die GitHub-Kommandozeile `gh` meist schon selbst – und das spart Kontext.",
    docsUrl: DOKU.mcp,
    installHinweis:
      "Die offizielle Doku zeigt den Befehl. Er braucht einen persönlichen GitHub-Token – den gibst du nur im Terminal ein, nie im Chat.",
    passtZuTools: [],
    passtZuZielen: ["bauen", "programmieren"],
    abErfahrung: "etwas",
    brauchtGithub: true,
    icon: "github",
  },
  {
    id: "context7",
    name: "Context7",
    wozu: "Holt aktuelle Dokumentation zu Programmier-Bibliotheken, damit Claude weniger veraltete oder erfundene Funktionen nutzt.",
    fuerWen: "Wer mit aktuellen Frameworks wie Next.js oder React baut.",
    voraussetzung: "Ein Projekt, das Programmier-Bibliotheken nutzt.",
    risiko: "Ein externer Dienst liefert Inhalte in dein Gespräch. Nur offizielle Quelle verwenden.",
    wannNicht: "Für Büroaufgaben, Texte oder Dateiordnung bringt es nichts.",
    docsUrl: "https://github.com/upstash/context7",
    installHinweis: "Einrichtung laut Anleitung des Anbieters. Bitte in der offiziellen Doku prüfen.",
    passtZuTools: [],
    passtZuZielen: ["programmieren", "bauen"],
    abErfahrung: "etwas",
    brauchtGithub: false,
    icon: "book",
  },
  {
    id: "playwright",
    name: "Playwright (Browser)",
    wozu: "Claude öffnet deine gebaute Website in einem Browser, klickt sich durch und macht Screenshots.",
    fuerWen: "Wer Websites oder Web-Apps baut und sie automatisch prüfen lassen will.",
    voraussetzung: "Ein Web-Projekt, das lokal im Browser läuft.",
    risiko: "Der Browser kann fremde Seiten laden. Nur eigene oder vertrauenswürdige Seiten öffnen lassen.",
    wannNicht: "Wenn du keine Website baust.",
    docsUrl: "https://github.com/microsoft/playwright-mcp",
    installHinweis: "Einrichtung laut Anleitung des Anbieters. Bitte in der offiziellen Doku prüfen.",
    passtZuTools: [],
    passtZuZielen: ["bauen", "programmieren"],
    abErfahrung: "etwas",
    brauchtGithub: false,
    icon: "globe",
  },
  {
    id: "websuche",
    name: "Websuche & Recherche",
    wozu: "Dienste wie Exa oder Firecrawl lassen Claude gezielt im Web suchen und Seiten auslesen.",
    fuerWen: "Wer viel recherchiert und Quellen gesammelt haben möchte.",
    voraussetzung: "Ein Konto beim jeweiligen Anbieter, oft mit API-Schlüssel.",
    risiko:
      "Webseiten können versteckte Anweisungen enthalten ([[prompt-injection|Prompt-Injection]]). Ergebnisse immer prüfen.",
    wannNicht: "Wenn deine Quellen schon als Dateien im Ordner liegen.",
    docsUrl: DOKU.mcp,
    installHinweis:
      "Kein Befehl in der Claude-Code-Doku. Folge der Anleitung des Anbieters – bitte in der offiziellen Doku prüfen.",
    passtZuTools: [],
    passtZuZielen: ["schreiben"],
    abErfahrung: "etwas",
    brauchtGithub: false,
    icon: "search",
  },
  {
    id: "google-drive",
    name: "Google Drive / Docs",
    wozu: "Claude liest Dokumente aus deinem Google Drive, etwa Konzepte oder Tabellen.",
    fuerWen: "Wer seine Unterlagen in Google Drive hat.",
    voraussetzung: "Ein Google-Konto. Mit claude.ai-Konto oft als „Connector“ verfügbar.",
    risiko: "Claude sieht, was du freigibst. Keine Ordner mit vertraulichen Daten verbinden.",
    wannNicht: "Wenn du die paar Dateien auch einfach in den Projektordner legen kannst.",
    docsUrl: CONNECTORS,
    installHinweis:
      "Auf claude.ai eingerichtete Connectors sind in Claude Code automatisch verfügbar. Details: bitte in der offiziellen Doku prüfen.",
    passtZuTools: ["google"],
    passtZuZielen: ["schreiben", "buero"],
    abErfahrung: "keine",
    brauchtGithub: false,
    icon: "file",
  },
  {
    id: "notion",
    name: "Notion",
    wozu: "Claude liest und aktualisiert Seiten und Datenbanken in Notion.",
    fuerWen: "Wer Notizen, Aufgaben oder Wissen in Notion pflegt.",
    voraussetzung: "Ein Notion-Konto. Die Anmeldung erfolgt im Browser.",
    risiko: "Claude kann Seiten ändern. Anfangs nur lesen lassen und Änderungen prüfen.",
    wannNicht: "Wenn du Notion kaum nutzt.",
    docsUrl: DOKU.mcp,
    installHinweis: "Befehl aus der offiziellen Doku, danach im Terminal `/mcp` zum Anmelden:",
    installFaktId: "mcp-notion",
    passtZuTools: ["notion"],
    passtZuZielen: ["schreiben", "buero", "ordnen"],
    abErfahrung: "keine",
    brauchtGithub: false,
    icon: "notebook",
  },
  {
    id: "slack",
    name: "Slack",
    wozu: "Claude liest Nachrichten aus Slack-Kanälen, etwa für Zusammenfassungen.",
    fuerWen: "Teams, die in Slack kommunizieren.",
    voraussetzung: "Ein Slack-Konto; im Firmen-Slack oft die Freigabe deiner IT.",
    risiko: "Firmen-Nachrichten sind oft vertraulich. Firmenregeln beachten.",
    wannNicht: "Auf dem Firmenrechner ohne Freigabe.",
    docsUrl: CONNECTORS,
    installHinweis:
      "Oft als claude.ai-Connector verfügbar. Einrichtung: bitte in der offiziellen Doku prüfen.",
    passtZuTools: ["slack"],
    passtZuZielen: ["buero", "schreiben"],
    abErfahrung: "keine",
    brauchtGithub: false,
    icon: "message",
  },
  {
    id: "jira-linear",
    name: "Jira / Linear",
    wozu: "Claude liest Tickets und kann sie nach getaner Arbeit aktualisieren.",
    fuerWen: "Wer in Projekten mit Ticket-System arbeitet.",
    voraussetzung: "Ein Konto bei Jira oder Linear und die Erlaubnis deines Teams.",
    risiko: "Änderungen an Tickets sehen alle im Team. Anfangs nur lesen lassen.",
    wannNicht: "Für private Projekte ohne Ticket-System.",
    docsUrl: DOKU.mcp,
    installHinweis:
      "Kein Befehl in der Claude-Code-Doku. Folge der Anleitung des Anbieters – bitte in der offiziellen Doku prüfen.",
    passtZuTools: ["jiralinear"],
    passtZuZielen: ["programmieren", "buero"],
    abErfahrung: "etwas",
    brauchtGithub: false,
    icon: "kanban",
  },
  {
    id: "kalender-mail",
    name: "Kalender & Mail",
    wozu: "Claude liest Termine und E-Mails, etwa für eine Tagesübersicht oder Antwort-Entwürfe.",
    fuerWen: "Wer viel Zeit mit Terminen und Posteingang verbringt.",
    voraussetzung: "Ein claude.ai-Konto mit eingerichtetem Connector (z. B. Gmail, Google Calendar, Microsoft 365).",
    risiko: "E-Mails sind oft vertraulich und können fremde Anweisungen enthalten. Nie automatisch senden lassen.",
    wannNicht: "Auf dem Firmenrechner ohne Freigabe oder wenn du mit sensiblen Daten arbeitest.",
    docsUrl: CONNECTORS,
    installHinweis:
      "Auf claude.ai eingerichtete Connectors sind in Claude Code automatisch verfügbar. Details: bitte in der offiziellen Doku prüfen.",
    passtZuTools: ["kalendermail"],
    passtZuZielen: ["buero"],
    abErfahrung: "keine",
    brauchtGithub: false,
    icon: "calendar",
  },
  {
    id: "datenbank",
    name: "Datenbank (nur lesend)",
    wozu: "Claude stellt Fragen direkt an deine Datenbank, etwa „Welche Produkte werden am häufigsten zurückgeschickt?“.",
    fuerWen: "Wer mit Datenbanken arbeitet und Auswertungen braucht.",
    voraussetzung: "Zugangsdaten mit reinen Leserechten.",
    risiko: "Mit Schreibrechten könnte Claude Daten verändern. Immer einen Nur-Lese-Zugang verwenden.",
    wannNicht: "Bei produktiven Datenbanken mit Kundendaten ohne Freigabe.",
    docsUrl: DOKU.mcp,
    installHinweis:
      "Die offizielle Doku zeigt ein Beispiel mit einem Nur-Lese-Zugang. Das Passwort gibst du nur im Terminal ein, nie im Chat.",
    passtZuTools: ["datenbank"],
    passtZuZielen: ["programmieren"],
    abErfahrung: "etwas",
    brauchtGithub: false,
    icon: "database",
  },
  {
    id: "sentry",
    name: "Sentry (später)",
    wozu: "Claude sieht Fehlerberichte deiner laufenden App und kann gezielt nach der Ursache suchen.",
    fuerWen: "Wer eine App veröffentlicht hat und Fehler überwacht.",
    voraussetzung: "Ein Sentry-Konto und eine App, die Fehler dorthin meldet.",
    risiko: "Fehlerberichte können Nutzerdaten enthalten. Datenschutz beachten.",
    wannNicht: "Solange du noch keine veröffentlichte App hast.",
    docsUrl: DOKU.mcp,
    installHinweis: "Befehl aus der offiziellen Doku, danach `/mcp` zum Anmelden:",
    installFaktId: "mcp-sentry",
    passtZuTools: [],
    passtZuZielen: ["programmieren"],
    abErfahrung: "gut",
    brauchtGithub: false,
    icon: "bug",
  },
];

export function findeMcp(id: string): Mcp | undefined {
  return mcps.find((m) => m.id === id);
}
