import {
  ArrowLeft,
  ArrowRight,
  BookOpen,
  Brain,
  Briefcase,
  Bug,
  Building2,
  Calendar,
  ChartColumn,
  Check,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleHelp,
  Clock,
  Cloud,
  Code,
  Coins,
  Compass,
  Copy,
  Cpu,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileStack,
  FileText,
  Flag,
  FlaskConical,
  Folder,
  FolderPlus,
  Footprints,
  Gamepad2,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  Hammer,
  Hand,
  HeartPulse,
  House,
  Image,
  Info,
  KeyRound,
  Laptop,
  Layers,
  Leaf,
  Lightbulb,
  ListChecks,
  Lock,
  LogIn,
  Mail,
  Map as MapIcon,
  Megaphone,
  Menu,
  MessageSquare,
  Monitor,
  Moon,
  NotebookPen,
  Package,
  Palette,
  PenLine,
  PiggyBank,
  Play,
  Plug,
  Printer,
  Quote,
  Receipt,
  Repeat,
  Rocket,
  RotateCcw,
  Save,
  Scale,
  Search,
  Server,
  ShieldCheck,
  SkipForward,
  Smartphone,
  Smile,
  Sparkle,
  Sparkles,
  Sprout,
  SquareKanban,
  SquareTerminal,
  Star,
  Sun,
  Table,
  Target,
  Timer,
  TreePine,
  TriangleAlert,
  Undo2,
  User,
  Users,
  Wallet,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/lib/icon-namen";

const ICONS: Record<IconName, LucideIcon> = {
  "alert": TriangleAlert,
  "book": BookOpen,
  "brain": Brain,
  "briefcase": Briefcase,
  "bug": Bug,
  "building": Building2,
  "calendar": Calendar,
  "chart": ChartColumn,
  "check": Check,
  "check-circle": CircleCheck,
  "circle": Circle,
  "clock": Clock,
  "cloud": Cloud,
  "code": Code,
  "coins": Coins,
  "compass": Compass,
  "copy": Copy,
  "cpu": Cpu,
  "database": Database,
  "download": Download,
  "eye": Eye,
  "eye-off": EyeOff,
  "file": FileText,
  "file-stack": FileStack,
  "flask": FlaskConical,
  "folder": Folder,
  "folder-plus": FolderPlus,
  "footprints": Footprints,
  "gamepad": Gamepad2,
  "gift": Gift,
  "github": GitBranch,
  "globe": Globe,
  "graduation": GraduationCap,
  "hammer": Hammer,
  "hand": Hand,
  "heart": HeartPulse,
  "help": CircleHelp,
  "home": House,
  "image": Image,
  "kanban": SquareKanban,
  "key": KeyRound,
  "laptop": Laptop,
  "layers": Layers,
  "list": ListChecks,
  "log-in": LogIn,
  "mail": Mail,
  "map": MapIcon,
  "megaphone": Megaphone,
  "message": MessageSquare,
  "monitor": Monitor,
  "moon": Moon,
  "notebook": NotebookPen,
  "package": Package,
  "palette": Palette,
  "pen": PenLine,
  "piggy": PiggyBank,
  "play": Play,
  "plug": Plug,
  "quote": Quote,
  "receipt": Receipt,
  "repeat": Repeat,
  "rocket": Rocket,
  "save": Save,
  "scale": Scale,
  "search": Search,
  "seedling": Sprout,
  "server": Server,
  "shield": ShieldCheck,
  "smartphone": Smartphone,
  "smile": Smile,
  "sparkles": Sparkles,
  "sprout": Leaf,
  "star": Star,
  "stars": Sparkle,
  "sun": Sun,
  "table": Table,
  "target": Target,
  "terminal": SquareTerminal,
  "timer": Timer,
  "tree": TreePine,
  "undo": Undo2,
  "user": User,
  "users": Users,
  "wallet": Wallet,
  "x": X,
  "zap": Zap,
  "arrow": ArrowRight,
  "back": ArrowLeft,
  "menu": Menu,
  "reset": RotateCcw,
  "print": Printer,
  "external": ExternalLink,
  "info": Info,
  "lightbulb": Lightbulb,
  "chevron": ChevronRight,
  "skip": SkipForward,
  "flag": Flag,
  "lock": Lock,
  "close": X,
};

type Props = { name: string; className?: string; size?: number; strokeWidth?: number };

/** Dekoratives Icon. Unbekannte Namen fallen auf einen Kreis zurück. */
export function Icon({ name, className, size = 20, strokeWidth = 1.75 }: Props) {
  const Komponente = ICONS[name as IconName] ?? Circle;
  return <Komponente aria-hidden="true" focusable="false" className={className} size={size} strokeWidth={strokeWidth} />;
}
